<a href="https://colab.research.google.com/github/jisoolee11/Deep-Learning/blob/main/DeepLearning%20for%20everyone/review_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>영화리뷰가 긍정적인지 부정적인지 예측하기

In [ ]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding 

In [ ]:
# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다', '한번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']

In [ ]:
# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0]) 

In [ ]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [ ]:
# 패딩, 서로 다른 길이의 데이터를 4로 맞춤
x = token.texts_to_sequences(docs)
padded_x =pad_sequences(x, 4)
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [ ]:
# 임베딩에 입력될 단어 수 지정
word_size = len(token.word_index)+1

In [ ]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 767ms/step - loss: 0.6932 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6911 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6889 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6868 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6847 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6826 - accuracy: 0.6000
Epoch 7/20
1/1 [==============================] - 0s 3ms/step - loss: 0.6805 - accuracy: 0.6000
Epoch 8/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6784 - accuracy: 0.6000
Epoch 9/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6763 - accuracy: 0.7000
Epoch 10/20
1/1 [==============================] - 0s 4ms/step - loss: 0.6741 - accuracy: 0.8000
Epoch 11/20
1/1 [====================