<a href="https://colab.research.google.com/github/jisoolee11/Deep-Learning/blob/main/MLschool/practice_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> 아이리스 품종 분류</h1>

- 아이리스:https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 과거의 데이터를 불러옵니다
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape =[4])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [ ]:
# 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs= 100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1360 - accuracy: 0.9667
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.1349 - accuracy: 0.9533
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 0.4128 - accuracy: 0.8533
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1521 - accuracy: 0.9400
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1122 - accuracy: 0.9733
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.2087 - accuracy: 0.9200
Epoch 7/100
5/5 [==============================] - 0s 4ms/step - loss: 0.1254 - accuracy: 0.9600
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1196 - accuracy: 0.9600
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1159 - accuracy: 0.9733
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1289 - accuracy: 0.9467
Epoch 11/100
5/5 [===========

In [ ]:
# 모델을 이용합니다.
model.predict(독립[0:5])

array([[9.99872327e-01, 2.43099657e-05, 1.03391241e-04],
       [9.99672890e-01, 9.70893743e-05, 2.30022444e-04],
       [9.99730527e-01, 6.15406971e-05, 2.07916280e-04],
       [9.99470651e-01, 1.98535417e-04, 3.30899464e-04],
       [9.99871492e-01, 2.38858102e-05, 1.04687635e-04]], dtype=float32)

In [ ]:
print(종속[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
# 학습한 가중치
model.get_weights()

[array([[ 0.54858947,  0.3208143 ,  0.3727774 ,  0.16377172,  0.19360375,
          0.17057462, -0.1970162 , -0.49898988],
        [ 0.1095374 ,  0.2475318 , -0.31089967, -0.36603674, -0.04688509,
          0.652453  , -0.22273424,  0.3769924 ],
        [-0.45416862,  0.17288966,  0.8393724 ,  0.49063402,  0.41284126,
          0.05864242,  0.52459306,  0.6534221 ],
        [-0.24276198,  0.4666043 ,  0.55162424,  0.28681612,  0.6933562 ,
         -0.00862592, -0.7406511 ,  0.41153577]], dtype=float32),
 array([ 0.24343729, -0.03273113,  0.1641508 , -0.04360808, -0.14984417,
         0.18124607, -0.01041265, -0.02011454], dtype=float32),
 array([[-0.1137299 ,  0.8972049 ,  0.06056142,  0.8085218 ,  0.7968869 ,
          0.39336625, -0.7852065 ,  0.63423234],
        [-0.10751545,  0.6361173 ,  0.5356922 , -0.4289464 , -0.19738694,
         -0.30869913,  0.2609561 , -0.22390623],
        [ 0.59817624, -0.24889706,  0.47319138,  0.07406242, -0.10564186,
         -0.18040577,  0.08421268,